FIND_PATH(HTTP_PARSER_INCLUDE_DIR NAMES http_parser.h)
FIND_LIBRARY(HTTP_PARSER_LIBRARY NAMES http_parser libhttp_parser)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HTTP_PARSER DEFAULT_MSG HTTP_PARSER_LIBRARY HTTP_PARSER_INCLUDE_DIR)

MARK_AS_ADVANCED(HTTP_PARSER_LIBRARY HTTP_PARSER_INCLUDE_DIR)

IF (HTTP_PARSER_FOUND)
	SET(HTTP_PARSER_LIBRARIES ${HTTP_PARSER_LIBRARY})
	SET(HTTP_PARSER_INCLUDE_DIRS ${HTTP_PARSER_INCLUDE_DIR})

	FILE(READ "${HTTP_PARSER_INCLUDE_DIR}/http_parser.h" http_parser_header)
	IF (http_parser_header)
		STRING(REGEX REPLACE ".*#define[\t ]+HTTP_PARSER_VERSION_MAJOR[\t ]+([0-9]+).*" "\\1" HTTP_PARSER_VERSION_MAJOR "${http_parser_header}")
		STRING(REGEX REPLACE ".*#define[\t ]+HTTP_PARSER_VERSION_MINOR[\t ]+([0-9]+).*" "\\1" HTTP_PARSER_VERSION_MINOR "${http_parser_header}")
	ELSE()
		UNSET(HTTP_PARSER_FOUND)
	ENDIF()
	UNSET(http_parser_header)
ENDIF()
