/*
 * Copyright (c), Edward Thomson <ethomson@edwardthomson.com>
 * All rights reserved.
 *
 * This file is part of adopt, distributed under the MIT license.
 * For full terms and conditions, see the included LICENSE file.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT.
 *
 * This file was produced by using the `rename.pl` script included with
 * adopt.  The command-line specified was:
 *
 * ./rename.pl cli_opt --filename=opt --include=cli.h --inline=GIT_INLINE --header-guard=CLI_opt_h__ --lowercase-status --without-usage
 */

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <assert.h>

#include "cli.h"
#include "opt.h"

#ifdef _WIN32
# include <Windows.h>
#else
# include <fcntl.h>
# include <sys/ioctl.h>
#endif

#ifdef _MSC_VER
# define alloca _alloca
#endif

#define spec_is_named_type(x) \
	((x)->type == CLI_OPT_TYPE_BOOL || \
	 (x)->type == CLI_OPT_TYPE_SWITCH || \
	 (x)->type == CLI_OPT_TYPE_VALUE)

GIT_INLINE(const cli_opt_spec *) spec_byname(
	cli_opt_parser *parser,
	const char *name,
	size_t namelen,
	int *is_converse)
{
	const cli_opt_spec *spec;

	*is_converse = 0;

	for (spec = parser->specs; spec->type; ++spec) {
		if (spec->type == CLI_OPT_TYPE_LITERAL && namelen == 0)
			return spec;

		/* Handle "no-" prefix for boolean types */
		if (spec->type == CLI_OPT_TYPE_BOOL &&
		    strlen(spec->name) + 3 == namelen &&
		    strncmp(name, "no-", 3) == 0 &&
		    strncmp(name + 3, spec->name, namelen) == 0) {
			*is_converse = 1;
			return spec;
		}

		if (spec_is_named_type(spec) &&
		    spec->name &&
		    strlen(spec->name) == namelen &&
		    strncmp(name, spec->name, namelen) == 0)
			return spec;
	}

	return NULL;
}

GIT_INLINE(const cli_opt_spec *) spec_byalias(cli_opt_parser *parser, char alias)
{
	const cli_opt_spec *spec;

	for (spec = parser->specs; spec->type; ++spec) {
		if (spec_is_named_type(spec) && alias == spec->alias)
			return spec;
	}

	return NULL;
}

GIT_INLINE(const cli_opt_spec *) spec_nextarg(cli_opt_parser *parser)
{
	const cli_opt_spec *spec;
	size_t args = 0;

	for (spec = parser->specs; spec->type; ++spec) {
		if (spec->type == CLI_OPT_TYPE_ARG) {
			if (args == parser->arg_idx) {
				parser->arg_idx++;
				return spec;
			}

			args++;
		}

		if (spec->type == CLI_OPT_TYPE_ARGS && args == parser->arg_idx)
			return spec;
	}

	return NULL;
}

GIT_INLINE(int) spec_is_choice(const cli_opt_spec *spec)
{
	return ((spec + 1)->type &&
	       ((spec + 1)->usage & CLI_OPT_USAGE_CHOICE));
}

/*
 * If we have a choice with switches and bare arguments, and we see
 * the switch, then we no longer expect the bare argument.
 */
GIT_INLINE(void) consume_choices(const cli_opt_spec *spec, cli_opt_parser *parser)
{
	/* back up to the beginning of the choices */
	while (spec->type && (spec->usage & CLI_OPT_USAGE_CHOICE))
		--spec;

	if (!spec_is_choice(spec))
		return;

	do {
		if (spec->type == CLI_OPT_TYPE_ARG)
			parser->arg_idx++;
		++spec;
	} while(spec->type && (spec->usage & CLI_OPT_USAGE_CHOICE));
}

static cli_opt_status_t parse_long(cli_opt *opt, cli_opt_parser *parser)
{
	const cli_opt_spec *spec;
	char *arg = parser->args[parser->idx++], *name = arg + 2, *eql;
	int converse = 0;
	size_t namelen;

	namelen = (eql = strrchr(arg, '=')) ? (size_t)(eql - name) : strlen(name);

	opt->arg = arg;

	if ((spec = spec_byname(parser, name, namelen, &converse)) == NULL) {
		opt->spec = NULL;
		opt->status = CLI_OPT_STATUS_UNKNOWN_OPTION;
		goto done;
	}

	opt->spec = spec;

	/* Future options parsed as literal */
	if (spec->type == CLI_OPT_TYPE_LITERAL)
		parser->in_literal = 1;

	else if (spec->type == CLI_OPT_TYPE_BOOL && spec->value)
		*((int *)spec->value) = !converse;

	else if (spec->type == CLI_OPT_TYPE_SWITCH && spec->value)
		*((int *)spec->value) = spec->switch_value;

	/* Parse values as "--foo=bar" or "--foo bar" */
	else if (spec->type == CLI_OPT_TYPE_VALUE) {
		if (eql && *(eql+1))
			opt->value = eql + 1;
		else if ((parser->idx + 1) <= parser->args_len)
			opt->value = parser->args[parser->idx++];

		if (spec->value)
			*((char **)spec->value) = opt->value;
	}

	/* Required argument was not provided */
	if (spec->type == CLI_OPT_TYPE_VALUE &&
	    !opt->value &&
	    !(spec->usage & CLI_OPT_USAGE_VALUE_OPTIONAL))
		opt->status = CLI_OPT_STATUS_MISSING_VALUE;
	else
		opt->status = CLI_OPT_STATUS_OK;

	consume_choices(opt->spec, parser);

done:
	return opt->status;
}

static cli_opt_status_t parse_short(cli_opt *opt, cli_opt_parser *parser)
{
	const cli_opt_spec *spec;
	char *arg = parser->args[parser->idx++], alias = *(arg + 1);

	opt->arg = arg;

	if ((spec = spec_byalias(parser, alias)) == NULL) {
		opt->spec = NULL;
		opt->status = CLI_OPT_STATUS_UNKNOWN_OPTION;
		goto done;
	}

	opt->spec = spec;

	if (spec->type == CLI_OPT_TYPE_BOOL && spec->value)
		*((int *)spec->value) = 1;

	if (spec->type == CLI_OPT_TYPE_SWITCH && spec->value)
		*((int *)spec->value) = spec->switch_value;

	/* Parse values as "-ifoo" or "-i foo" */
	if (spec->type == CLI_OPT_TYPE_VALUE) {
		if (strlen(arg) > 2)
			opt->value = arg + 2;
		else if ((parser->idx + 1) <= parser->args_len)
			opt->value = parser->args[parser->idx++];

		if (spec->value)
			*((char **)spec->value) = opt->value;
	}

	/* Required argument was not provided */
	if (spec->type == CLI_OPT_TYPE_VALUE && !opt->value)
		opt->status = CLI_OPT_STATUS_MISSING_VALUE;
	else
		opt->status = CLI_OPT_STATUS_OK;

	consume_choices(opt->spec, parser);

done:
	return opt->status;
}

static cli_opt_status_t parse_arg(cli_opt *opt, cli_opt_parser *parser)
{
	const cli_opt_spec *spec = spec_nextarg(parser);

	opt->spec = spec;
	opt->arg = parser->args[parser->idx];

	if (!spec) {
		parser->idx++;
		opt->status = CLI_OPT_STATUS_UNKNOWN_OPTION;
	} else if (spec->type == CLI_OPT_TYPE_ARGS) {
		if (spec->value)
			*((char ***)spec->value) = &parser->args[parser->idx];

		/* Args consume all the remaining arguments. */
		parser->in_args = (parser->args_len - parser->idx);
		parser->idx = parser->args_len;
		opt->args_len = parser->in_args;
		opt->status = CLI_OPT_STATUS_OK;
	} else {
		if (spec->value)
			*((char **)spec->value) = parser->args[parser->idx];

		parser->idx++;
		opt->status = CLI_OPT_STATUS_OK;
	}

	return opt->status;
}

void cli_opt_parser_init(
	cli_opt_parser *parser,
	const cli_opt_spec specs[],
	char **args,
	size_t args_len)
{
	assert(parser);

	memset(parser, 0x0, sizeof(cli_opt_parser));

	parser->specs = specs;
	parser->args = args;
	parser->args_len = args_len;
}

cli_opt_status_t cli_opt_parser_next(cli_opt *opt, cli_opt_parser *parser)
{
	assert(opt && parser);

	memset(opt, 0x0, sizeof(cli_opt));

	if (parser->idx >= parser->args_len) {
		opt->args_len = parser->in_args;
		return CLI_OPT_STATUS_DONE;
	}

	/* Handle arguments in long form, those beginning with "--" */
	if (strncmp(parser->args[parser->idx], "--", 2) == 0 &&
		!parser->in_literal)
		return parse_long(opt, parser);

	/* Handle arguments in short form, those beginning with "-" */
	else if (strncmp(parser->args[parser->idx], "-", 1) == 0 &&
		!parser->in_literal)
		return parse_short(opt, parser);

	/* Handle "free" arguments, those without a dash */
	else
		return parse_arg(opt, parser);
}

GIT_INLINE(int) spec_included(const cli_opt_spec **specs, const cli_opt_spec *spec)
{
	const cli_opt_spec **i;

	for (i = specs; *i; ++i) {
		if (spec == *i)
			return 1;
	}

	return 0;
}

static cli_opt_status_t validate_required(
	cli_opt *opt,
	const cli_opt_spec specs[],
	const cli_opt_spec **given_specs)
{
	const cli_opt_spec *spec, *required;
	int given;

	/*
	 * Iterate over the possible specs to identify requirements and
	 * ensure that those have been given on the command-line.
	 * Note that we can have required *choices*, where one in a
	 * list of choices must be specified.
	 */
	for (spec = specs, required = NULL, given = 0; spec->type; ++spec) {
		if (!required && (spec->usage & CLI_OPT_USAGE_REQUIRED)) {
			required = spec;
			given = 0;
		} else if (!required) {
			continue;
		}

		if (!given)
			given = spec_included(given_specs, spec);

		/*
		 * Validate the requirement unless we're in a required
		 * choice.  In that case, keep the required state and
		 * validate at the end of the choice list.
		 */
		if (!spec_is_choice(spec)) {
			if (!given) {
				opt->spec = required;
				opt->status = CLI_OPT_STATUS_MISSING_ARGUMENT;
				break;
			}

			required = NULL;
			given = 0;
		}
	}

	return opt->status;
}

cli_opt_status_t cli_opt_parse(
	cli_opt *opt,
	const cli_opt_spec specs[],
	char **args,
	size_t args_len)
{
	cli_opt_parser parser;
	const cli_opt_spec **given_specs;
	size_t given_idx = 0;

	cli_opt_parser_init(&parser, specs, args, args_len);

	given_specs = alloca(sizeof(const cli_opt_spec *) * (args_len + 1));

	while (cli_opt_parser_next(opt, &parser)) {
		if (opt->status != CLI_OPT_STATUS_OK &&
		    opt->status != CLI_OPT_STATUS_DONE)
			return opt->status;

		if ((opt->spec->usage & CLI_OPT_USAGE_STOP_PARSING))
			return (opt->status = CLI_OPT_STATUS_DONE);

		given_specs[given_idx++] = opt->spec;
	}

	given_specs[given_idx] = NULL;

	return validate_required(opt, specs, given_specs);
}

static int spec_name_fprint(FILE *file, const cli_opt_spec *spec)
{
	int error;

	if (spec->type == CLI_OPT_TYPE_ARG)
		error = fprintf(file, "%s", spec->value_name);
	else if (spec->type == CLI_OPT_TYPE_ARGS)
		error = fprintf(file, "%s", spec->value_name);
	else if (spec->alias && !(spec->usage & CLI_OPT_USAGE_SHOW_LONG))
		error = fprintf(file, "-%c", spec->alias);
	else
		error = fprintf(file, "--%s", spec->name);

	return error;
}

int cli_opt_status_fprint(
	FILE *file,
	const char *command,
	const cli_opt *opt)
{
	const cli_opt_spec *choice;
	int error;

	if (command && (error = fprintf(file, "%s: ", command)) < 0)
		return error;

	switch (opt->status) {
	case CLI_OPT_STATUS_DONE:
		error = fprintf(file, "finished processing arguments (no error)\n");
		break;
	case CLI_OPT_STATUS_OK:
		error = fprintf(file, "no error\n");
		break;
	case CLI_OPT_STATUS_UNKNOWN_OPTION:
		error = fprintf(file, "unknown option: %s\n", opt->arg);
		break;
	case CLI_OPT_STATUS_MISSING_VALUE:
		if ((error = fprintf(file, "argument '")) < 0 ||
		    (error = spec_name_fprint(file, opt->spec)) < 0 ||
		    (error = fprintf(file, "' requires a value.\n")) < 0)
			break;
		break;
	case CLI_OPT_STATUS_MISSING_ARGUMENT:
		if (spec_is_choice(opt->spec)) {
			int is_choice = 1;

			if (spec_is_choice((opt->spec)+1))
				error = fprintf(file, "one of");
			else
				error = fprintf(file, "either");

			if (error < 0)
				break;

			for (choice = opt->spec; is_choice; ++choice) {
				is_choice = spec_is_choice(choice);

				if (!is_choice)
					error = fprintf(file, " or");
				else if (choice != opt->spec)
					error = fprintf(file, ",");

				if ((error < 0) ||
				    (error = fprintf(file, " '")) < 0 ||
				    (error = spec_name_fprint(file, choice)) < 0 ||
				    (error = fprintf(file, "'")) < 0)
					break;

				if (!spec_is_choice(choice))
					break;
			}

			if ((error < 0) ||
			    (error = fprintf(file, " is required.\n")) < 0)
				break;
		} else {
			if ((error = fprintf(file, "argument '")) < 0 ||
			    (error = spec_name_fprint(file, opt->spec)) < 0 ||
			    (error = fprintf(file, "' is required.\n")) < 0)
				break;
		}

		break;
	default:
		error = fprintf(file, "unknown status: %d\n", opt->status);
		break;
	}

	return error;
}

