name: OSS-Fuzz
on:
  pull_request:
  push:
    branches:
      - stable
      - develop
      - pre-release
      - '2.*'
    tags:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'zlib-ng'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'zlib-ng'
        fuzz-seconds: 600
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
