MACRO(ENABLE_WARNINGS flag)
	ADD_C_FLAG_IF_SUPPORTED(-W${flag})
ENDMACRO()

MACRO(DISABLE_WARNINGS flag)
	ADD_C_FLAG_IF_SUPPORTED(-Wno-${flag})
ENDMACRO()

IF(ENABLE_WERROR)
	ADD_C_FLAG_IF_SUPPORTED(-Werror)
ENDIF()
