IF (USE_NTLMCLIENT)
	SET(GIT_NTLM 1 PARENT_SCOPE)
	ADD_SUBDIRECTORY("${libgit2_SOURCE_DIR}/deps/ntlmclient" "${libgit2_BINARY_DIR}/deps/ntlmclient")
	ADD_LIBRARY(NtlmClient ALIAS ntlmclient)
	ADD_FEATURE_INFO(ntlmclient ON "using ntlmclient")
ELSE()
	ADD_LIBRARY(NtlmClient INTERFACE)
	ADD_FEATURE_INFO(ntlmclient OFF "NTLM authentication support for Unix")
ENDIF()
